### ISSUE TITLE
GPU evaluate is not work?

### ISSUE THREAD

**Issue by haihai-self** [ehw-fit/tf-approximate#11]
Hi my name is moh.
Thank for your opening source. I followed the steps you gave to build the environment, but the result is incorrect when using GPU for evaluation, and the result is correct when using CPU evaluation.

[error](https://homework-image.oss-cn-beijing.aliyuncs.com/image/1594610814.jpg)

**Comment by FilipVaverka** [comment]
Hi,

this is probably caused by build system, which defaults to compile only for Maxwell GPUs (sm_50). Passing -DTFAPPROX_CUDA_ARCHS="75" flag to cmake configuration step should set NVCC to compile for your Turing GPU. Fat binary for multiple GPU architectures can be generated by specifying list such as "50;60;75".

**Comment by haihai-self** [comment]
It worked! Thanks for the help, it's really a great job!
